version: '3.8'

services:
  app:
    build: .
    container_name: menu_cafe_app
    ports:
      - "${PORT_APP:-8081}:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD:-supersecretpassword}
      - DB_NAME=${DB_NAME:-cafe_db}

  db:
    image: mysql:8.0
    container_name: menu_cafe_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-supersecretpassword}
      MYSQL_DATABASE: ${DB_NAME:-cafe_db}
    ports:
      - "${PORT_DB:-3307}:3306"
    volumes:
      - menu_cafe_db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  menu_cafe_db_data: